### ISSUE TITLE
[EP] Reduce font size for Disclaimer

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/CoA-schemas#43]
## Describe the problem
Certificates contain a Declaration of Conformance. In many cases a generic disclaimer is part of this section. In the current JSON schema there is not possibility to differentiate these properties - the workaround is to concatenate the strings which does not match the data structures in existing QM system. 

## Specify the details
Add optional property `Disclaimer` to object `Certificate` 

```
"Disclaimer": {
    "title": "Disclaimer",
    "description": "A general disclaimer for the entire document",
    "type": "string"
},
```

- [x] Update schema
- [x] Update CoA documentation
- [x] Add test

## Explain the benefits
Properties can be clearly separated in the data and the rendering. In the rendering the font size could be reduced as proposed in another EP

**Comment by eamon0989** [comment]
The latest PRs (https://github.com/thematerials-network/CoA-schemas/pull/60 and https://github.com/s1seven/schema-tools/pull/175) add support for this change, here are the rendered results:

Screenshot of Disclaimer rendered in PDF:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/21305201/194836304-32af534d-2eea-47e0-8041-b02eecfce851.png">

Screenshot of Disclaimer rendered in HTML:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21305201/194836391-d61e4940-aea9-4185-a22c-8e96d59b543f.png">
