### ISSUE TITLE
[EP] Make `Analysis` optional

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/CoA-schemas#47]
## Describe the problem
For certificates of type EN 10204 2.1 no inspections might be provided.

## Specify the details
- [x] Remove `Analysis` as mandatory in the list of required objects for a certificate.
- [x] Update schema-tools
- [x] Adapt HTML rendering
- [x] Adapt PDF rendering
- [x] Add new fixture to validate correct implementation
- [x] Check if documentation has to be updated in https://github.com/thematerials-network/CoA-documentation

## Explain the benefits
Certificate type is supported.

**Comment by eamon0989** [comment]
Done, here is a screenshot of a rendered PDF with the above changes for documentation purposes:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/21305201/194509940-3897deb2-305b-4948-b1e4-c22ee7e3fb30.png">
