### ISSUE TITLE
fix: coa pdf rendering looks for `AddressLine1` instead of `Street`

### ISSUE THREAD

**Issue by eamon0989** [thematerials-network/CoA-schemas#59]
**Describe the bug**

The CoA schema has been updated to use the `Company` schema-definition in v1.0.0. `AddressLine1` and `2` have been replaced with the property `Street` which can be either a string or an array. The rendering of the html has been updated, but not the PDF. This leaves an empty line in the PDF where the Address should be.

**To Reproduce**

Look at the PDF in fixtures for v1.0.0 and compare it to the one from v0.2.0

**Expected behavior**

I expect the `Street` property to be rendered in the CoA PDF.

**Screenshots**

CoA v1.0.0
<img width="773" alt="image" src="https://user-images.githubusercontent.com/21305201/194043833-6a62285b-1435-4316-92fa-0598c9637c3b.png">

CoA v0.2.0
<img width="899" alt="image" src="https://user-images.githubusercontent.com/21305201/194043886-4e2cbe98-11c7-4bad-928f-8fc85f891871.png">

**Comment by stiebitzhofer** [comment]
I think we should not display empty lines. Can you play with it as there are 3 Street entries possible?

**Comment by eamon0989** [comment]
I've already updated it in https://github.com/s1seven/schema-tools/pull/173, it no longer leaves empty lines, here is a screenshot of the latest implementation:
![image](https://user-images.githubusercontent.com/21305201/194074532-5f46a008-c06c-489d-8810-39ae9df4f6ea.png)

**Comment by stiebitzhofer** [comment]
Excellent!
