### ISSUE TITLE
[EP] Make `Identifiers` optional

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/CoA-schemas#62]
## Describe the problem
In ERPs, receivers of certificates are not necessarily mapped or linked with legal entities. Therefore an identifier such as VAT or DUNS is not available by default for the generation of material certificates; only the email address is maintained.

To reduce effort and friction in switching receivers to digital material certificates, the email address is initially sufficient. 

## Specify the details
- [x] Switch `identifiers` in `company.json` to `optional`.
- [x] Update https://materialidentity.org/coa/#coa-structure 

## Explain the benefits
Issuers can switch receivers of certificates without having to add `VAT` and/or `DUNS`.

**Comment by getlarge** [comment]
fixed in #64
