### ISSUE TITLE
[EP] Differentiate between receiver of goods and certificates

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/CoA-schemas#63]
## Describe the problem
The design of the JSON Schema version 1.0.0 assumes that the receiver of the goods is also the receiver of the certificates. This assumption proves invalid in many real-world cases.

## Specify the details
To enable a smooth transition from the 1.1.0 format, the following steps are proposed:
- [x] Add party `GoodsReceiver` to `Parties`.
- [x] Change inline documentation of `Receiver` to the receiver of certificates, not goods.
- [ ] Change documentation on https://materialidentity.org.
- [x] Change the label for Receiver to `Certificate receiver` (currently `Goods receiver`). 

Implementation of https://github.com/thematerials-network/CoA-schemas/issues/62 should be considered a prerequisite.

## Explain the benefits
JSON Schema matches current business practices.

**Comment by ChristopheRigaud** [comment]
I agree

**Comment by stiebitzhofer** [comment]
@ChristopheRigaud One question: should the GoodsReceiver be mandatory?

**Comment by stiebitzhofer** [comment]
And the Receiver (the certificate receiver)? Mandatory or not?

**Comment by stiebitzhofer** [comment]
As discussed with experts, we leave the certificate receiver optional.
